server:
  port: 8585

spring:
  application:
    name: Raphael-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: Media-Service
            uri: lb://media-service
            predicates:
              - Path=/api/media/**
          - id: Edufy-Service
            uri: lb://edufy-service
            predicates:
              - Path=/api/edufy/**
          - id: Customer-Service
            uri: lb://customer-service
            predicates:
              - Path=/api/customer/**

#eureka:
  #client:
    #service-url:
      #defaultZone: http://raphael-server:8761/eureka/ # docker
      defaultZone: http://localhost:8761/eureka/ #din dator


  instance:
    prefer-ip-address: true
