server:
  port: 8585

spring:
  application:
    name: Raphael-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: Media-Service
            uri: lb://media-service
            predicates:
              - Path=/api/media/**
          - id: Edufy-Service
            uri: lb://edufy-service
            predicates:
              - Path=/api/edufy/**
          - id: Customer-Service
            uri: lb://customer-service
            predicates:
              - Path=/api/customer/**

#eureka:
  #client:
    #service-url:
      #defaultZone: http://media-service:8761/eureka/ #Den här är för docker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #De här är för när du kör från din dator
  instance:
    prefer-ip-address: true
